### PR TITLE
Minor modifications to fit our use case

### PR DESCRIPTION
**Pull request by harsh4786**
I'm Harsh from the Redacted Capital team & we'd like to add these patches to our yellowstone-grpc-client module
- Added a constructor for `GeyserGrpcClient`
- Make `InterceptorFn` and it's underlying token publicly accessible
- Add a `max_decoding_message_size()` fn to fit our use case

### CODE REVIEW

**Comment by fanatid** [comment]
Why do not use client from original repo? https://github.com/rpcpool/yellowstone-grpc

**Comment by harsh4786** [comment]
> Why do not use client from original repo? https://github.com/rpcpool/yellowstone-grpc

I could but then i'd face dependency conflicts with the `yellowstone-grpc-proto` crate from this repo where we have the previous changes that you merged [here](https://github.com/rpcpool/yellowstone-grpc-gamma/commit/72dd0e94ff28eba442fe2bde5da28bf06bcd1b89). So I just decided to push these changes in this repo itself to make it more easier for imports

**Comment by harsh4786** [comment]
These crates are very sensitive to version conflicts.

**Comment by fanatid** [comment]
oh, I see, let me just create a new release here based on the original repo

**Comment by harsh4786** [comment]
Thanks!

**Comment by fanatid** [comment]
Done https://github.com/rpcpool/yellowstone-grpc-gamma/releases/tag/v1.14.2%2Bsolana.1.17.33.gamma

**Comment by harsh4786** [comment]
well actually solana versions need to be v1.16 since v1.17 have version conflicts @fanatid

**Pull request closed without merging**
